# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'UrbanEaterDriver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UrbanEaterDriver

  pod 'Alamofire', '~> 4.5'
  pod 'ReachabilitySwift'
  pod 'Google'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacesSearchController'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SDWebImage/WebP'
  pod 'SwiftyJSON'
  pod 'SwiftMessages', '~> 5.0.1'
  pod 'MMMaterialDesignSpinner'
  pod 'SwiftLocation', '~> 3.2.3'
  pod 'EZSwiftExtensions'
  pod 'HTHorizontalSelectionList', '~> 0.7.4'
  pod 'IQKeyboardManagerSwift'



end
